# Generated by Django 4.1.1 on 2022-11-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '__first__'),
        ('responses', '0002_rename_jobresponses_responsesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancymodel'),
        ),
    ]
