# Generated by Django 4.1.1 on 2022-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=55, verbose_name='Должность')),
                ('company_name', models.CharField(max_length=55, verbose_name='Название компании')),
                ('salary', models.IntegerField(verbose_name='Доход')),
                ('city', models.CharField(max_length=35, verbose_name='Город')),
                ('description', models.CharField(max_length=700, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ('id',),
            },
        ),
    ]
