# Generated by Django 3.0 on 2022-10-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='ПЕРСОНАЛЬНЫЕ ДАННЫЕ')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('data_of_birth', models.DateTimeField(max_length=10, verbose_name='Дата рождения')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=8, verbose_name='Пол')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('country', models.CharField(max_length=60, verbose_name='Страна')),
                ('hometown', models.CharField(max_length=100, verbose_name='Родной город/аул')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('postindex', models.IntegerField(verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Резюме пользователя',
                'verbose_name_plural': 'Резюме пользователей',
            },
        ),
    ]
