# Generated by Django 4.1.3 on 2022-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='country',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='postindex',
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.CharField(choices=[('Have work experience', 'Have'), ('No work expirience', 'Have Not')], default='Have work experience', max_length=35, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='data_of_birth',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=8, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hometown',
            field=models.CharField(max_length=100, verbose_name='Город проживания'),
        ),
    ]
