# Generated by Django 4.1.3 on 2022-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_adress_remove_resume_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='data_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
