# Generated by Django 4.1.3 on 2022-11-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_data_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.CharField(choices=[('Есть опыт работы', 'Have'), ('Нет опыта работы', 'Have Not')], default='Есть опыт работы', max_length=35, verbose_name='Опыт работы'),
        ),
    ]
