# Generated by Django 4.1.1 on 2022-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=10, upload_to='', verbose_name='Примеры работ (портфолио)')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ManyToManyField(to='resume.images'),
        ),
    ]
